/**
 * Mapping of German Pokémon names to English names.
 * Keys are lowercase German names for case-insensitive lookup.
 * Only contains entries where the German name differs from the English name.
 */
export const DE_TO_EN: Record<string, string> = {
  // ── Gen 1 (Kanto #001–#151) ─────────────────────────────────────────────
  'bisasam': 'Bulbasaur',
  'bisaknosp': 'Ivysaur',
  'bisaflor': 'Venusaur',
  'glumanda': 'Charmander',
  'glutexo': 'Charmeleon',
  'glurak': 'Charizard',
  'schiggy': 'Squirtle',
  'schillok': 'Wartortle',
  'turtok': 'Blastoise',
  'raupy': 'Caterpie',
  'safcon': 'Metapod',
  'smettbo': 'Butterfree',
  'hornliu': 'Weedle',
  'bibor': 'Beedrill',
  'taubsi': 'Pidgey',
  'tauboga': 'Pidgeotto',
  'tauboss': 'Pidgeot',
  'rattfratz': 'Rattata',
  'rattikarl': 'Raticate',
  'habitak': 'Spearow',
  'ibitak': 'Fearow',
  'rettan': 'Ekans',
  'sandan': 'Sandshrew',
  'sandamer': 'Sandslash',
  'piepi': 'Clefairy',
  'pixi': 'Clefable',
  'vulnona': 'Ninetales',
  'pummeluff': 'Jigglypuff',
  'knuddeluff': 'Wigglytuff',
  'myrapla': 'Oddish',
  'duflor': 'Gloom',
  'giflor': 'Vileplume',
  'parasek': 'Parasect',
  'bluzuk': 'Venonat',
  'omot': 'Venomoth',
  'digda': 'Diglett',
  'digdri': 'Dugtrio',
  'mauzi': 'Meowth',
  'snobilikat': 'Persian',
  'enton': 'Psyduck',
  'entoron': 'Golduck',
  'menki': 'Mankey',
  'rasaff': 'Primeape',
  'fukano': 'Growlithe',
  'arkani': 'Arcanine',
  'quapsel': 'Poliwag',
  'quaputzi': 'Poliwhirl',
  'quappo': 'Poliwrath',
  'simsala': 'Alakazam',
  'machollo': 'Machop',
  'maschock': 'Machoke',
  'machomei': 'Machamp',
  'knofensa': 'Bellsprout',
  'ultrigaria': 'Weepinbell',
  'sarzenia': 'Victreebel',
  'tentacha': 'Tentacool',
  'tentoxa': 'Tentacruel',
  'kleinstein': 'Geodude',
  'georok': 'Graveler',
  'geowaz': 'Golem',
  'ponita': 'Ponyta',
  'gallopa': 'Rapidash',
  'flegmon': 'Slowpoke',
  'lahmus': 'Slowbro',
  'magnetilo': 'Magnemite',
  'porenta': "Farfetch'd",
  'dodu': 'Doduo',
  'dodri': 'Dodrio',
  'jurob': 'Seel',
  'jugong': 'Dewgong',
  'sleima': 'Grimer',
  'sleimok': 'Muk',
  'muschas': 'Shellder',
  'austos': 'Cloyster',
  'nebulak': 'Gastly',
  'alpollo': 'Haunter',
  'traumato': 'Drowzee',
  'voltobal': 'Voltorb',
  'lektrobal': 'Electrode',
  'owei': 'Exeggcute',
  'kokowei': 'Exeggutor',
  'tragosso': 'Cubone',
  'knogga': 'Marowak',
  'kicklee': 'Hitmonlee',
  'nockchan': 'Hitmonchan',
  'schlurp': 'Lickitung',
  'smogon': 'Koffing',
  'smogmog': 'Weezing',
  'rihorn': 'Rhyhorn',
  'rizeros': 'Rhydon',
  'chaneira': 'Chansey',
  'kangama': 'Kangaskhan',
  'seeper': 'Horsea',
  'seemon': 'Seadra',
  'goldini': 'Goldeen',
  'golking': 'Seaking',
  'sterndu': 'Staryu',
  'pantimos': 'Mr. Mime',
  'sichlor': 'Scyther',
  'rossana': 'Jynx',
  'elektek': 'Electabuzz',
  'karpador': 'Magikarp',
  'garados': 'Gyarados',
  'evoli': 'Eevee',
  'aquana': 'Vaporeon',
  'blitza': 'Jolteon',
  'flamara': 'Flareon',
  'amonitas': 'Omanyte',
  'amoroso': 'Omastar',
  'relaxo': 'Snorlax',
  'arktos': 'Articuno',
  'lavados': 'Moltres',
  'dragonir': 'Dragonair',
  'dragoran': 'Dragonite',
  'mewtu': 'Mewtwo',

  // ── Gen 2 (Johto #152–#251) ─────────────────────────────────────────────
  'endivie': 'Chikorita',
  'lorblatt': 'Bayleef',
  'meganie': 'Meganium',
  'feurigel': 'Cyndaquil',
  'igelavar': 'Quilava',
  'tornupto': 'Typhlosion',
  'karnimani': 'Totodile',
  'tyracroc': 'Croconaw',
  'impergator': 'Feraligatr',
  'wiesor': 'Sentret',
  'wiesenior': 'Furret',
  'hoothoot': 'Hoothoot',
  'noctuh': 'Noctowl',
  'lediba': 'Ledyba',
  'ledian': 'Ledian',
  'webarak': 'Spinarak',
  'iksbat': 'Crobat',
  'lampi': 'Chinchou',
  'lanturn': 'Lanturn',
  'pichu': 'Pichu',
  'pii': 'Cleffa',
  'fluffeluff': 'Igglybuff',
  'togepi': 'Togepi',
  'togetic': 'Togetic',
  'natu': 'Natu',
  'xatu': 'Xatu',
  'voltilamm': 'Mareep',
  'waaty': 'Flaaffy',
  'ampharox': 'Ampharos',
  'blubella': 'Bellossom',
  'marill': 'Marill',
  'azumarill': 'Azumarill',
  'mogelbaum': 'Sudowoodo',
  'quaxo': 'Politoed',
  'hoppspross': 'Hoppip',
  'hubelupf': 'Skiploom',
  'papungha': 'Jumpluff',
  'griffel': 'Aipom',
  'yanma': 'Yanma',
  'sonnkern': 'Sunkern',
  'sonnflora': 'Sunflora',
  'felino': 'Wooper',
  'morlord': 'Quagsire',
  'psiana': 'Espeon',
  'nachtara': 'Umbreon',
  'kramurx': 'Murkrow',
  'laschoking': 'Slowking',
  'traunfugil': 'Misdreavus',
  'icognito': 'Unown',
  'woingenau': 'Wobbuffet',
  'tannza': 'Pineco',
  'forstellka': 'Forretress',
  'dummisel': 'Dunsparce',
  'skorgla': 'Gligar',
  'stahlos': 'Steelix',
  'baldorfish': 'Qwilfish',
  'scherox': 'Scizor',
  'pottrott': 'Shuckle',
  'skaraborn': 'Heracross',
  'sniebel': 'Sneasel',
  'teddiursa': 'Teddiursa',
  'ursaring': 'Ursaring',
  'schneckmag': 'Slugma',
  'magcargo': 'Magcargo',
  'quiekel': 'Swinub',
  'keifel': 'Piloswine',
  'corasonn': 'Corsola',
  'remoraid': 'Remoraid',
  'octillery': 'Octillery',
  'botogel': 'Delibird',
  'mantax': 'Mantine',
  'panzaeron': 'Skarmory',
  'hunduster': 'Houndour',
  'hundemon': 'Houndoom',
  'seedraking': 'Kingdra',
  'phanpy': 'Phanpy',
  'donphan': 'Donphan',
  'porygon2': 'Porygon2',
  'damhirplex': 'Stantler',
  'farbeagle': 'Smeargle',
  'rabauz': 'Tyrogue',
  'kapoera': 'Hitmontop',
  'kussilla': 'Smoochum',
  'elekid': 'Elekid',
  'magby': 'Magby',
  'miltank': 'Miltank',
  'heiteira': 'Blissey',
  'raikou': 'Raikou',
  'entei': 'Entei',
  'suicune': 'Suicune',
  'larvitar': 'Larvitar',
  'pupitar': 'Pupitar',
  'despotar': 'Tyranitar',
  'lugia': 'Lugia',
  'ho-oh': 'Ho-Oh',
  'celebi': 'Celebi',

  // ── Gen 3 (Hoenn #252–#386) ─────────────────────────────────────────────
  'geckarbor': 'Treecko',
  'reptain': 'Grovyle',
  'gewaldro': 'Sceptile',
  'flemmli': 'Torchic',
  'jungglut': 'Combusken',
  'lohgock': 'Blaziken',
  'hydropi': 'Mudkip',
  'moorabbel': 'Marshtomp',
  'sumpex': 'Swampert',
  'fiffyen': 'Poochyena',
  'magnayen': 'Mightyena',
  'zigzachs': 'Zigzagoon',
  'geradaks': 'Linoone',
  'waumpel': 'Wurmple',
  'schaloko': 'Silcoon',
  'papinella': 'Beautifly',
  'panekon': 'Cascoon',
  'pudox': 'Dustox',
  'loturzel': 'Lotad',
  'lombrero': 'Lombre',
  'kappalores': 'Ludicolo',
  'samurzel': 'Seedot',
  'blanas': 'Nuzleaf',
  'tengulist': 'Shiftry',
  'schwalbini': 'Taillow',
  'schwalboss': 'Swellow',
  'trasla': 'Ralts',
  'guardevoir': 'Gardevoir',
  'gehweiher': 'Surskit',
  'maskeregen': 'Masquerain',
  'knilz': 'Shroomish',
  'kapilz': 'Breloom',
  'bummelz': 'Slakoth',
  'muntier': 'Vigoroth',
  'letarking': 'Slaking',
  'ninjatom': 'Shedinja',
  'flurmel': 'Whismur',
  'krakeelo': 'Loudred',
  'krawumms': 'Exploud',
  'nasgnet': 'Nosepass',
  'eneco': 'Skitty',
  'enekoro': 'Delcatty',
  'zobiris': 'Sableye',
  'flunkifer': 'Mawile',
  'stollunior': 'Aron',
  'stollrak': 'Lairon',
  'stolloss': 'Aggron',
  'meditalis': 'Medicham',
  'frizelbliz': 'Electrike',
  'voltenso': 'Manectric',
  'schluppuck': 'Gulpin',
  'schlukwech': 'Swalot',
  'kanivanha': 'Carvanha',
  'tohaido': 'Sharpedo',
  'camaub': 'Numel',
  'qurtel': 'Torkoal',
  'groink': 'Grumpig',
  'pandir': 'Spinda',
  'knacklion': 'Trapinch',
  'libelldra': 'Flygon',
  'tuska': 'Cacnea',
  'noktuska': 'Cacturne',
  'wablu': 'Swablu',
  'sengo': 'Zangoose',
  'vipitis': 'Seviper',
  'lunastein': 'Lunatone',
  'sonnfel': 'Solrock',
  'schmerbe': 'Barboach',
  'welsar': 'Whiscash',
  'krebscorps': 'Corphish',
  'krebutack': 'Crawdaunt',
  'puppance': 'Baltoy',
  'lepumentas': 'Claydol',
  'liliep': 'Lileep',
  'wielie': 'Cradily',
  'barschwa': 'Feebas',
  'formeo': 'Castform',
  'zwirrlicht': 'Duskull',
  'zwirrklop': 'Dusclops',
  'palimpalim': 'Chimecho',
  'isso': 'Wynaut',
  'schneppke': 'Snorunt',
  'firnontor': 'Glalie',
  'seemops': 'Spheal',
  'seejong': 'Sealeo',
  'walraisa': 'Walrein',
  'perlu': 'Clamperl',
  'aalabyss': 'Huntail',
  'saganabyss': 'Gorebyss',
  'liebiskus': 'Luvdisc',
  'kindwurm': 'Bagon',
  'draschel': 'Shelgon',
  'brutalanda': 'Salamence',
  'tanhel': 'Beldum',

  // ── Gen 4 (Sinnoh #387–#493) ────────────────────────────────────────────
  'chelast': 'Turtwig',
  'chelcarain': 'Grotle',
  'chelterrar': 'Torterra',
  'panflam': 'Chimchar',
  'panpyro': 'Monferno',
  'panferno': 'Infernape',
  'plinfa': 'Piplup',
  'pliprin': 'Prinplup',
  'impoleon': 'Empoleon',
  'staralili': 'Starly',
  'staravia': 'Staravia',
  'staraptor': 'Staraptor',
  'bidiza': 'Bidoof',
  'bidifas': 'Bibarel',
  'zirpurze': 'Kricketot',
  'zirpeise': 'Kricketune',
  'sheinux': 'Shinx',
  'luxio': 'Luxio',
  'luxtra': 'Luxray',
  'knospi': 'Budew',
  'roselia': 'Roselia',
  'roserade': 'Roserade',
  'koknodon': 'Cranidos',
  'rameidon': 'Rampardos',
  'schilterus': 'Shieldon',
  'bollterus': 'Bastiodon',
  'burmy': 'Burmy',
  'burmadame': 'Wormadam',
  'moterpel': 'Mothim',
  'wadribie': 'Combee',
  'honweisel': 'Vespiquen',
  'bamelin': 'Buizel',
  'bojelin': 'Floatzel',
  'kikugi': 'Cherubi',
  'kinoso': 'Cherrim',
  'schalellos': 'Shellos',
  'gastrodon': 'Gastrodon',
  'ambidiffel': 'Ambipom',
  'driftlon': 'Drifloon',
  'drifzepeli': 'Drifblim',
  'haspiror': 'Buneary',
  'schlapor': 'Lopunny',
  'traunmagil': 'Mismagius',
  'kramshef': 'Honchkrow',
  'charmian': 'Glameow',
  'shnurgarst': 'Purugly',
  'klingplim': 'Chingling',
  'skunkapuh': 'Stunky',
  'skuntank': 'Skuntank',
  'bronzel': 'Bronzor',
  'bronzong': 'Bronzong',
  'bonsly': 'Bonsly',
  'mobai': 'Bonsly',
  'pantimimi': 'Mime Jr.',
  'wonneira': 'Happiny',
  'plaudagei': 'Chatot',
  'kryppuk': 'Spiritomb',
  'kaumalat': 'Gible',
  'knarksel': 'Gabite',
  'knakrack': 'Garchomp',
  'mampfaxo': 'Munchlax',
  'riolu': 'Riolu',
  'lucario': 'Lucario',
  'hippopotas': 'Hippopotas',
  'hippoterus': 'Hippowdon',
  'pionskora': 'Skorupi',
  'piondragi': 'Drapion',
  'glibunkel': 'Croagunk',
  'toxiquak': 'Toxicroak',
  'venuflibis': 'Carnivine',
  'mantirps': 'Mantyke',
  'shnebedeck': 'Snover',
  'rexblisar': 'Abomasnow',
  'snibunna': 'Weavile',
  'schlurplek': 'Lickilicky',
  'rihornior': 'Rhyperior',
  'tangoloss': 'Tangrowth',
  'elevoltek': 'Electivire',
  'magbrant': 'Magmortar',
  'togekiss': 'Togekiss',
  'yanmega': 'Yanmega',
  'folipurba': 'Leafeon',
  'glaziola': 'Glaceon',
  'porygon-z': 'Porygon-Z',
  'skorgro': 'Gliscor',
  'mamutel': 'Mamoswine',
  'porygon z': 'Porygon-Z',
  'galagladi': 'Gallade',
  'voluminas': 'Probopass',
  'zwirfinst': 'Dusknoir',
  'frosdedje': 'Froslass',
  'rotom': 'Rotom',
  'selfe': 'Uxie',
  'vesprit': 'Mesprit',
  'tobutz': 'Azelf',
  'dialga': 'Dialga',
  'palkia': 'Palkia',
  'giratina': 'Giratina',
  'heatran': 'Heatran',
  'regigigas': 'Regigigas',
  'cresselia': 'Cresselia',
  'phione': 'Phione',
  'manaphy': 'Manaphy',
  'darkrai': 'Darkrai',
  'shaymin': 'Shaymin',
  'arceus': 'Arceus',

  // ── Gen 5 (Unova #494–#649) ─────────────────────────────────────────────
  'serpifeu': 'Snivy',
  'efoserp': 'Servine',
  'serpiroyal': 'Serperior',
  'floink': 'Tepig',
  'ferkokel': 'Pignite',
  'flambirex': 'Emboar',
  'ottaro': 'Oshawott',
  'zwottronin': 'Dewott',
  'admurai': 'Samurott',
  'nagelotz': 'Patrat',
  'kukmarda': 'Watchog',
  'yorkleff': 'Lillipup',
  'terribark': 'Herdier',
  'bissbark': 'Stoutland',
  'felilou': 'Purrloin',
  'kleoparda': 'Liepard',
  'vegimak': 'Pansage',
  'vegichita': 'Simisage',
  'grillmak': 'Pansear',
  'grillchita': 'Simisear',
  'sodamak': 'Panpour',
  'sodachita': 'Simipour',
  'somniam': 'Munna',
  'somnivora': 'Musharna',
  'dusselgurr': 'Pidove',
  'navitaub': 'Tranquill',
  'fasasnob': 'Unfezant',
  'elezeba': 'Blitzle',
  'zebritz': 'Zebstrika',
  'kiesling': 'Roggenrola',
  'sedimantur': 'Boldore',
  'brockoloss': 'Gigalith',
  'fleknoil': 'Woobat',
  'fletiamo': 'Swoobat',
  'rotomurf': 'Drilbur',
  'stalobor': 'Excadrill',
  'ohrdoch': 'Audino',
  'praktibalk': 'Timburr',
  'strepoli': 'Gurdurr',
  'meistagrif': 'Conkeldurr',
  'schallquap': 'Tympole',
  'mebrana': 'Palpitoad',
  'branawarz': 'Seismitoad',
  'jiutesto': 'Throh',
  'karadonis': 'Sawk',
  'strawickl': 'Sewaddle',
  'folikon': 'Swadloon',
  'matrifol': 'Leavanny',
  'toxiped': 'Venipede',
  'rollum': 'Whirlipede',
  'cerapendra': 'Scolipede',
  'waumboll': 'Cottonee',
  'elfun': 'Whimsicott',
  'lilminip': 'Petilil',
  'dressella': 'Lilligant',
  'barschuft': 'Basculin',
  'ganovil': 'Sandile',
  'rokkaiman': 'Krokorok',
  'rabigator': 'Krookodile',
  'flampion': 'Darumaka',
  'flampivian': 'Darmanitan',
  'maracamba': 'Maractus',
  'lithomith': 'Dwebble',
  'castellith': 'Crustle',
  'zurrokex': 'Scraggy',
  'irokex': 'Scrafty',
  'symvolara': 'Sigilyph',
  'makabaja': 'Yamask',
  'echnatoll': 'Cofagrigus',
  'galapaflos': 'Tirtouga',
  'karippas': 'Carracosta',
  'flapteryx': 'Archen',
  'aeropteryx': 'Archeops',
  'unratütox': 'Trubbish',
  'deponitox': 'Garbodor',
  'picochilla': 'Minccino',
  'chillabell': 'Cinccino',
  'mollimorba': 'Gothita',
  'hypnomorba': 'Gothorita',
  'morbitesse': 'Gothitelle',
  'monozyto': 'Solosis',
  'mitodos': 'Duosion',
  'zytomega': 'Reuniclus',
  'piccolente': 'Ducklett',
  'swaroness': 'Swanna',
  'gelatini': 'Vanillite',
  'gelatroppo': 'Vanillish',
  'gelatwino': 'Vanilluxe',
  'sesokitz': 'Deerling',
  'kronjuwild': 'Sawsbuck',
  'laukaps': 'Karrablast',
  'cavalanzas': 'Escavalier',
  'tarnpignon': 'Foongus',
  'hutsassa': 'Amoonguss',
  'quabbel': 'Frillish',
  'apoquallyp': 'Jellicent',
  'mamolida': 'Alomomola',
  'wattzapf': 'Joltik',
  'voltula': 'Galvantula',
  'kastadur': 'Ferroseed',
  'tentantel': 'Ferrothorn',
  'klikk': 'Klink',
  'kliklak': 'Klang',
  'klikdiklak': 'Klinklang',
  'zapplardin': 'Tynamo',
  'zapplalek': 'Eelektrik',
  'zapplarang': 'Eelektross',
  'pygraulon': 'Elgyem',
  'megalon': 'Beheeyem',
  'lichtel': 'Litwick',
  'laternecto': 'Lampent',
  'skelabra': 'Chandelure',
  'milza': 'Axew',
  'sharfax': 'Fraxure',
  'maxax': 'Haxorus',
  'petznief': 'Cubchoo',
  'siberio': 'Beartic',
  'frigometri': 'Cryogonal',
  'schnuthelm': 'Shelmet',
  'hydragil': 'Accelgor',
  'flunschlik': 'Stunfisk',
  'lin-fu': 'Mienfoo',
  'wie-shu': 'Mienshao',
  'shardrago': 'Druddigon',
  'golbit': 'Golett',
  'golgantes': 'Golurk',
  'gladiantri': 'Pawniard',
  'caesurio': 'Bisharp',
  'bisofank': 'Bouffalant',
  'geronimatz': 'Rufflet',
  'washakwil': 'Braviary',
  'skallyk': 'Vullaby',
  'grypheldis': 'Mandibuzz',
  'furnifraß': 'Heatmor',
  'fermicula': 'Durant',
  'kapuno': 'Deino',
  'duodino': 'Zweilous',
  'trikephalo': 'Hydreigon',
  'ignivor': 'Larvesta',
  'ramoth': 'Volcarona',
  'kobalium': 'Cobalion',
  'terrakium': 'Terrakion',
  'viridium': 'Virizion',
  'boreos': 'Tornadus',
  'voltolos': 'Thundurus',
  'demeteros': 'Landorus',

  // ── Gen 6 (Kalos #650–#721) ─────────────────────────────────────────────
  'igamaro': 'Chespin',
  'igastarnish': 'Quilladin',
  'brigaron': 'Chesnaught',
  'fynx': 'Fennekin',
  'rutena': 'Braixen',
  'fennexis': 'Delphox',
  'froxy': 'Froakie',
  'amphizel': 'Frogadier',
  'quajutsu': 'Greninja',
  'scoppel': 'Bunnelby',
  'grebbit': 'Diggersby',
  'dartiri': 'Fletchling',
  'dartignis': 'Fletchinder',
  'fiaro': 'Talonflame',
  'purmel': 'Scatterbug',
  'puponcho': 'Spewpa',
  'leufeo': 'Litleo',
  'pyroleo': 'Pyroar',
  'mähikel': 'Skiddo',
  'chevrumm': 'Gogoat',
  'pam-pam': 'Pancham',
  'pandagro': 'Pangoro',
  'coiffwaff': 'Furfrou',
  'psiau': 'Espurr',
  'psiaugon': 'Meowstic',
  'gramokles': 'Honedge',
  'duokles': 'Doublade',
  'durengard': 'Aegislash',
  'parfi': 'Spritzee',
  'parfinesse': 'Aromatisse',
  'flauschling': 'Swirlix',
  'sabbaione': 'Slurpuff',
  'iscalar': 'Inkay',
  'calamanero': 'Malamar',
  'bithora': 'Binacle',
  'thanathora': 'Barbaracle',
  'algitt': 'Skrelp',
  'tandrak': 'Dragalge',
  'scampisto': 'Clauncher',
  'wummer': 'Clawitzer',
  'eguana': 'Helioptile',
  'elezard': 'Heliolisk',
  'balgoras': 'Tyrunt',
  'monargoras': 'Tyrantrum',
  'amarino': 'Amaura',
  'amagarga': 'Aurorus',
  'feelinara': 'Sylveon',
  'resladero': 'Hawlucha',
  'rocara': 'Carbink',
  'viscora': 'Goomy',
  'viscargot': 'Sliggoo',
  'viscogon': 'Goodra',
  'clavion': 'Klefki',
  'paragoni': 'Phantump',
  'trombork': 'Trevenant',
  'irrbis': 'Pumpkaboo',
  'pumpdjinn': 'Gourgeist',
  'arktip': 'Bergmite',
  'arktilas': 'Avalugg',
  'ef-em': 'Noibat',
  'uhafnir': 'Noivern',

  // ── Gen 7 (Alola #722–#809) ─────────────────────────────────────────────
  'bauz': 'Rowlet',
  'arboretoss': 'Dartrix',
  'silvarro': 'Decidueye',
  'flamiau': 'Litten',
  'miezunder': 'Torracat',
  'fuegro': 'Incineroar',
  'robball': 'Popplio',
  'marikeck': 'Brionne',
  'primarene': 'Primarina',
  'peppeck': 'Pikipek',
  'trompeck': 'Trumbeak',
  'tukanon': 'Toucannon',
  'mangunior': 'Yungoos',
  'manguspektor': 'Gumshoos',
  'mabula': 'Grubbin',
  'akkup': 'Charjabug',
  'donarion': 'Vikavolt',
  'krabbox': 'Crabrawler',
  'krawell': 'Crabominable',
  'choreogel': 'Oricorio',
  'wommel': 'Cutiefly',
  'bandelby': 'Ribombee',
  'wuffels': 'Rockruff',
  'wolwerock': 'Lycanroc',
  'lusardin': 'Wishiwashi',
  'garstella': 'Mareanie',
  'aggrostella': 'Toxapex',
  'pampuli': 'Mudbray',
  'pampross': 'Mudsdale',
  'araqua': 'Dewpider',
  'aranestro': 'Araquanid',
  'imantis': 'Fomantis',
  'mantidea': 'Lurantis',
  'bubungus': 'Morelull',
  'lamellux': 'Shiinotic',
  'molunk': 'Salandit',
  'amfira': 'Salazzle',
  'velursi': 'Stufful',
  'kosturso': 'Bewear',
  'frubberl': 'Bounsweet',
  'frubaila': 'Steenee',
  'fruyal': 'Tsareena',
  'curelei': 'Comfey',
  'kommandutan': 'Oranguru',
  'quartermak': 'Passimian',
  'reißlaus': 'Wimpod',
  'tectass': 'Golisopod',
  'sankabuh': 'Sandygast',
  'colossand': 'Palossand',
  'gufa': 'Pyukumuku',
  'typ:null': 'Type: Null',
  'amigento': 'Silvally',
  'meteno': 'Minior',
  'koalelu': 'Komala',
  'tortunator': 'Turtonator',
  'mimigma': 'Mimikyu',
  'knirfish': 'Bruxish',
  'sen-long': 'Drampa',
  'moruda': 'Dhelmise',
  'miniras': 'Jangmo-o',
  'mediras': 'Hakamo-o',
  'grandiras': 'Kommo-o',
  'kapu-riki': 'Tapu Koko',
  'kapu-fala': 'Tapu Lele',
  'kapu-toro': 'Tapu Bulu',
  'kapu-kime': 'Tapu Fini',
  'cosmovum': 'Cosmoem',
  'anego': 'Nihilego',
  'masskito': 'Buzzwole',
  'schabelle': 'Pheromosa',
  'voltriant': 'Xurkitree',
  'kaguron': 'Celesteela',
  'katagami': 'Kartana',
  'schlingking': 'Guzzlord',
  'venicro': 'Poipole',
  'agoyon': 'Naganadel',
  'muramura': 'Stakataka',
  'kopplosio': 'Blacephalon',

  // ── Gen 8 (Galar/Hisui #810–#905) ───────────────────────────────────────
  'chimpep': 'Grookey',
  'chimstix': 'Thwackey',
  'gortrom': 'Rillaboom',
  'hopplo': 'Scorbunny',
  'kickerlo': 'Raboot',
  'liberlo': 'Cinderace',
  'memmeon': 'Sobble',
  'phlegleon': 'Drizzile',
  'intelleon': 'Inteleon',
  'raffel': 'Skwovet',
  'schlaraffel': 'Greedent',
  'meikro': 'Rookidee',
  'kranoviz': 'Corvisquire',
  'krarmor': 'Corviknight',
  'sensect': 'Blipbug',
  'keradar': 'Dottler',
  'maritellit': 'Orbeetle',
  'kleptifux': 'Nickit',
  'gaunux': 'Thievul',
  'cottini': 'Gossifleur',
  'cottomi': 'Eldegoss',
  'wolly': 'Wooloo',
  'zwollock': 'Dubwool',
  'kamehaps': 'Chewtle',
  'kamalm': 'Drednaw',
  'voldi': 'Yamper',
  'bellektro': 'Boltund',
  'klonkett': 'Rolycoly',
  'wagong': 'Carkol',
  'montecarbo': 'Coalossal',
  'knapfel': 'Applin',
  'drapfel': 'Flapple',
  'schlapfel': 'Appletun',
  'salanga': 'Silicobra',
  'sanaconda': 'Sandaconda',
  'urgl': 'Cramorant',
  'pikuda': 'Arrokuda',
  'barrakiefa': 'Barraskewda',
  'riffex': 'Toxtricity',
  'thermopod': 'Sizzlipede',
  'infernopod': 'Centiskorch',
  'klopptopus': 'Clobbopus',
  'kaocto': 'Grapploct',
  'fatalitee': 'Sinistea',
  'mortipot': 'Polteageist',
  'brimova': 'Hatenna',
  'brimano': 'Hattrem',
  'silembrim': 'Hatterene',
  'bähmon': 'Impidimp',
  'pelzebub': 'Morgrem',
  'olangaar': 'Grimmsnarl',
  'barrikadax': 'Obstagoon',
  'mauzinger': 'Perrserker',
  'gorgasonn': 'Cursola',
  'lauchzelot': "Sirfetch'd",
  'pantifrost': 'Mr. Rime',
  'oghnatoll': 'Runerigus',
  'hokumil': 'Milcery',
  'pokusan': 'Alcremie',
  'legios': 'Falinks',
  'britzigel': 'Pincurchin',
  'snomnom': 'Snom',
  'mottineva': 'Frosmoth',
  'humanolith': 'Stonjourner',
  'kubuin': 'Eiscue',
  'servol': 'Indeedee',
  'kupfanti': 'Cufant',
  'patinaraja': 'Copperajah',
  'lectragon': 'Dracozolt',
  'lecryodon': 'Arctozolt',
  'pescragon': 'Dracovish',
  'pescryodon': 'Arctovish',
  'grolldra': 'Dreepy',
  'phandra': 'Drakloak',
  'katapuldra': 'Dragapult',
  'endynalos': 'Eternatus',
  'dakuma': 'Kubfu',
  'wulaosu': 'Urshifu',
  'polaross': 'Glastrier',
  'phantoros': 'Spectrier',
  'coronospa': 'Calyrex',
  'damythir': 'Wyrdeer',
  'axantor': 'Kleavor',
  'salmagnis': 'Basculegion',
  'myriador': 'Overqwil',
  'cupidos': 'Enamorus',

  // ── Gen 9 (Paldea #906–#1025) ───────────────────────────────────────────
  'felori': 'Sprigatito',
  'feliospa': 'Floragato',
  'maskagato': 'Meowscarada',
  'krokel': 'Fuecoco',
  'lokroko': 'Crocalor',
  'skelokrok': 'Skeledirge',
  'kwaks': 'Quaxly',
  'fuentente': 'Quaxwell',
  'bailonda': 'Quaquaval',
  'ferkuli': 'Lechonk',
  'fragrunz': 'Oinkologne',
  'tarundel': 'Tarountula',
  'spinjitzu': 'Spidops',
  'micrick': 'Nymble',
  'loklario': 'Lokix',
  'pamamo': 'Pawmo',
  'pamomamo': 'Pawmot',
  'zwieps': 'Tandemaus',
  'famieps': 'Maushold',
  'hefel': 'Fidough',
  'backel': 'Dachsbun',
  'olini': 'Smoliv',
  'oliva': 'Dolliv',
  'olithena': 'Arboliva',
  'krawalloro': 'Squawkabilly',
  'geosali': 'Nacli',
  'saltigant': 'Naclstack',
  'saltigantor': 'Garganacl',
  'knarbon': 'Charcadet',
  'crimanzo': 'Armarouge',
  'azugladis': 'Ceruledge',
  'blipp': 'Tadbulb',
  'wampitz': 'Bellibolt',
  'voltrel': 'Wattrel',
  'voltrean': 'Kilowattrel',
  'mobtiff': 'Maschiff',
  'mastifioso': 'Mabosstiff',
  'sproxi': 'Shroodle',
  'grombock': 'Grafaiai',
  'wirrlicht': 'Bramblin',
  'skelokorn': 'Brambleghast',
  'tentagra': 'Toedscool',
  'tenterra': 'Toedscruel',
  'klippella': 'Klawf',
  'chilingel': 'Capsakid',
  'halupenjo': 'Scovillain',
  'relluk': 'Rellor',
  'skarabaks': 'Rabsca',
  'flattutu': 'Flittle',
  'aperla': 'Espathra',
  'forgita': 'Tinkatink',
  'tafforgita': 'Tinkatuff',
  'granforgita': 'Tinkaton',
  'schligda': 'Wiglett',
  'schligdri': 'Wugtrio',
  'atomboss': 'Bombirdier',
  'delfinator': 'Finizen',
  'kraftle': 'Varoom',
  'ravylon': 'Revavroom',
  'motodor': 'Cyclizar',
  'schlurm': 'Orthworm',
  'lumispross': 'Glimmet',
  'lumiflora': 'Glimmora',
  'gruff': 'Greavard',
  'friedwuff': 'Houndstone',
  'flaminkno': 'Flamigo',
  'flaniwal': 'Cetoddle',
  'kolowal': 'Cetitan',
  'agiluza': 'Veluza',
  'heerashai': 'Dondozo',
  'nigiragi': 'Tatsugiri',
  'epitaff': 'Annihilape',
  'suelord': 'Clodsire',
  'dummimisel': 'Dudunsparce',
  'gladimperio': 'Kingambit',
  'riesenzahn': 'Great Tusk',
  'brüllschweif': 'Scream Tail',
  'wutpilz': 'Brute Bonnet',
  'flatterhaar': 'Flutter Mane',
  'kriechflügel': 'Slither Wing',
  'sandfell': 'Sandy Shocks',
  'eisenrad': 'Iron Treads',
  'eisenbündel': 'Iron Bundle',
  'eisenhand': 'Iron Hands',
  'eisenhaupt': 'Iron Jugulis',
  'eisenfalter': 'Iron Moth',
  'eisendorn': 'Iron Thorns',
  'frospino': 'Frigibax',
  'cryospino': 'Arctibax',
  'espinodon': 'Baxcalibur',
  'gierspenst': 'Gimmighoul',
  'monetigo': 'Gholdengo',
  'chongjian': 'Wo-Chien',
  'baojian': 'Chien-Pao',
  'dinglu': 'Ting-Lu',
  'yuyu': 'Chi-Yu',
  'brüllmond': 'Roaring Moon',
  'eisenblüte': 'Iron Valiant',
  'windewoge': 'Walking Wake',
  'eisenblatt': 'Iron Leaves',
  'adebom': 'Dipplin',
  'mortcha': 'Poltchageist',
  'fatalitcha': 'Sinistcha',
  'boninu': 'Okidogi',
  'benesaru': 'Munkidori',
  'beatori': 'Fezandipiti',
  'hydrapfel': 'Hydrapple',
  'furienblitz': 'Gouging Fire',
  'tobelblitz': 'Raging Bolt',
  'eisenfels': 'Iron Boulder',
  'eisenkrone': 'Iron Crown',

};

/**
 * Translates a German Pokémon name (or a name containing a German Pokémon name)
 * to the corresponding English name. Returns the translated string if a German
 * name was found, or null if no translation is available.
 *
 * Examples:
 *   translateGermanName('Glurak')      → 'Charizard'
 *   translateGermanName('Glurak EX')   → 'Charizard EX'
 *   translateGermanName('Bisasam V')   → 'Bulbasaur V'
 *   translateGermanName('Charizard')   → null  (already English)
 *   translateGermanName('mewtu')       → 'Mewtwo'
 */
export function translateGermanName(query: string): string | null {
  const trimmed = query.trim();
  if (!trimmed) return null;

  // Try full query first (handles names with spaces like "Mr. Mime")
  const fullLower = trimmed.toLowerCase();
  if (DE_TO_EN[fullLower]) return DE_TO_EN[fullLower]!;

  // Split and try first token, preserving any suffix (EX, GX, V, VMAX …)
  const tokens = trimmed.split(/\s+/);
  if (tokens.length === 0) return null;

  const firstName = tokens[0]!;
  const firstLower = firstName.toLowerCase();

  if (DE_TO_EN[firstLower]) {
    const englishName = DE_TO_EN[firstLower]!;
    const rest = tokens.slice(1).join(' ');
    return rest ? `${englishName} ${rest}` : englishName;
  }

  // Try first two tokens (e.g. "Mr Mime" written without a dot)
  if (tokens.length >= 2) {
    const twoTokensLower = `${tokens[0]} ${tokens[1]}`.toLowerCase();
    if (DE_TO_EN[twoTokensLower]) {
      const englishName = DE_TO_EN[twoTokensLower]!;
      const rest = tokens.slice(2).join(' ');
      return rest ? `${englishName} ${rest}` : englishName;
    }
  }

  return null;
}

/**
 * Same as translateGermanName but also tries fuzzy / prefix matching.
 * Used by the scanner where OCR may produce slightly garbled text.
 *
 * Fuzzy rules:
 *  1. Forward: OCR appended noise   – "garadosu" starts with DB key "garados" → Gyarados
 *  2. Reverse: OCR truncated name   – "karpado" is prefix of DB key "karpador" (≤2 chars short) → Magikarp
 */
export function fuzzyTranslateGermanName(query: string): string | null {
  // Try exact match first
  const exact = translateGermanName(query);
  if (exact !== null) return exact;

  const trimmed = query.trim();
  if (!trimmed) return null;
  const tokens = trimmed.split(/\s+/);
  const firstName = tokens[0]!;
  const firstLower = firstName.toLowerCase();
  if (firstLower.length < 3) return null;

  const suffix = tokens.slice(1).join(' ');

  // 1. Forward prefix: OCR text starts with a known DB key ("garadosu" → "garados")
  for (const [key, english] of Object.entries(DE_TO_EN)) {
    if (key.length >= 4 && firstLower.startsWith(key)) {
      return suffix ? `${english} ${suffix}` : english;
    }
  }

  // 2. Reverse prefix: known DB key starts with OCR text (OCR cut off ≤2 chars)
  if (firstLower.length >= 4) {
    for (const [key, english] of Object.entries(DE_TO_EN)) {
      if (key.length > firstLower.length && key.length - firstLower.length <= 2 && key.startsWith(firstLower)) {
        return suffix ? `${english} ${suffix}` : english;
      }
    }
  }

  return null;
}
